project:
  type: book
  output-dir: _book

book:
  title: "R para Ciência de Dados (2ª edição)"
  reader-mode: true

  page-footer:
    left: |
      R para Ciência de Dados (2ª edição) foi escrito por Hadley Wickham, Mine
      Çetinkaya-Rundel, e Garrett Grolemund.
    right: |
      Este livro foi contruído com <a href="https://quarto.org/">Quarto</a>.
  cover-image: cover.jpg
  favicon: cover.jpg
  site-url: https://cienciadedatos.github.io/pt-r4ds/
  repo-url: https://github.com/cienciadedatos/pt-r4ds/
  repo-branch: main
  repo-actions: [edit, issue]
  chapters:
    - index.qmd
    - preface-2e.qmd
    - intro.qmd
    - part: whole-game.qmd
      chapters:
        - data-visualize.qmd
        - workflow-basics.qmd
        - data-transform.qmd
        - workflow-style.qmd
        - data-tidy.qmd
        - workflow-scripts.qmd
        - data-import.qmd
        - workflow-help.qmd

    - part: visualize.qmd
      chapters:
        - layers.qmd
        - EDA.qmd
        - communication.qmd

    - part: transform.qmd
      chapters:
        - logicals.qmd
        - numbers.qmd
        - strings.qmd
        - regexps.qmd
        - factors.qmd
        - datetimes.qmd
        - missing-values.qmd
        - joins.qmd

    - part: import.qmd
      chapters:
        - spreadsheets.qmd
        - databases.qmd
        - arrow.qmd
        - rectangling.qmd
        - webscraping.qmd

    - part: program.qmd
      chapters:
        - functions.qmd
        - iteration.qmd
        - base-R.qmd

    - part: communicate.qmd
      chapters:
        - quarto.qmd
        - quarto-formats.qmd

format:
  html:
    theme:
      - cosmo
      - r4ds.scss
    code-link: true

    author-meta: "Hadley Wickham, Mine Çetinkaya-Rundel, e Garrett Grolemund"
    include-in-header: "plausible.html"
    callout-appearance: simple

editor: visual
lang: pt
